// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-tvhPkeFk56KR15zQLGGJRs0c1jhbOvs',
    appId: '1:407371478908:web:25d3f9c6a4623be06ad6f9',
    messagingSenderId: '407371478908',
    projectId: 'ci-cd-fc881',
    authDomain: 'ci-cd-fc881.firebaseapp.com',
    storageBucket: 'ci-cd-fc881.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYfosaoFxcfEo8m5bDFAf5B9yhlvYqqpM',
    appId: '1:407371478908:android:42d9d176da5a55b06ad6f9',
    messagingSenderId: '407371478908',
    projectId: 'ci-cd-fc881',
    storageBucket: 'ci-cd-fc881.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFd6FyrX1Nlt-GD0YDbRG3z4-10dqBM7s',
    appId: '1:407371478908:ios:9d8b9a58d5c5a0ff6ad6f9',
    messagingSenderId: '407371478908',
    projectId: 'ci-cd-fc881',
    storageBucket: 'ci-cd-fc881.firebasestorage.app',
    iosBundleId: 'com.example.learnCiCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFd6FyrX1Nlt-GD0YDbRG3z4-10dqBM7s',
    appId: '1:407371478908:ios:9d8b9a58d5c5a0ff6ad6f9',
    messagingSenderId: '407371478908',
    projectId: 'ci-cd-fc881',
    storageBucket: 'ci-cd-fc881.firebasestorage.app',
    iosBundleId: 'com.example.learnCiCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-tvhPkeFk56KR15zQLGGJRs0c1jhbOvs',
    appId: '1:407371478908:web:b6b4b5edef1c7c806ad6f9',
    messagingSenderId: '407371478908',
    projectId: 'ci-cd-fc881',
    authDomain: 'ci-cd-fc881.firebaseapp.com',
    storageBucket: 'ci-cd-fc881.firebasestorage.app',
  );
}
